In [23]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Pichau\Downloads\idVoo,empresaAerea,numeroVoo,codeAutoriz.txt")

In [14]:
df[df['numeroVoo'] == 2419].sort_values('numeroVoo', ascending=True)

,idVoo,empresaAerea,numeroVoo,codeAutorizacao,codeTipoLinha,aerodromoOrigem,aerodromoDestino,partidaPrevista,partidaReal,chegadaPrevista,chegadaReal,situacaoVoo,codeJustificativa,anoRef,nomeArquivo,data_hora_clima
0,AZU-2419-SBCF-SBGR-201503302122,AZU,2419,0,N,SBCF,SBGR,2015-03-30 21:22:00,2015-03-30 21:12:00,2015-03-30 23:00:00,2015-03-30 22:30:00,REALIZADO,HD,2015,VRA_20153.csv,2015-03-30 21:00:00
1,AZU-2419-SBCF-SBGR-201503302122,AZU,2419,0,N,SBCF,SBGR,2015-03-30 21:22:00,2015-03-30 21:12:00,2015-03-30 23:00:00,2015-03-30 22:30:00,REALIZADO,HD,2015,VRA_20153.csv,2015-03-30 21:00:00
2,AZU-2419-SBCF-SBGR-201503302122,AZU,2419,0,N,SBCF,SBGR,2015-03-30 21:22:00,2015-03-30 21:12:00,2015-03-30 23:00:00,2015-03-30 22:30:00,REALIZADO,HD,2015,VRA_20153.csv,2015-03-30 21:00:00

In [ ]:
df['linhaDuplicada'] = df.duplicated(keep=False)

In [32]:
# Seleciona as duas linhas para comparação
linha_0 = df.iloc[1]
linha_2 = df.iloc[2]

# Itera sobre as colunas e mostra onde elas divergem
for col in df.columns:
    val0 = linha_0[col]
    val2 = linha_2[col]
    if val0 != val2:
        print(f"Diferença encontrada na coluna: {col}")
        print(f"Linha 0: '{val0}' (Tipo: {type(val0)})")
        print(f"Linha 2: '{val2}' (Tipo: {type(val2)})")
        print("-" * 30)
    else:
        print(f'Coluna {col}: tudo certo!')

Coluna idVoo: tudo certo!
Coluna empresaAerea: tudo certo!
Coluna numeroVoo: tudo certo!
Coluna codeAutorizacao: tudo certo!
Coluna codeTipoLinha: tudo certo!
Coluna aerodromoOrigem: tudo certo!
Coluna aerodromoDestino: tudo certo!
Coluna partidaPrevista: tudo certo!
Coluna partidaReal: tudo certo!
Coluna chegadaPrevista: tudo certo!
Coluna chegadaReal: tudo certo!
Coluna situacaoVoo: tudo certo!
Coluna codeJustificativa: tudo certo!
Coluna anoRef: tudo certo!
Coluna nomeArquivo: tudo certo!
Coluna data_hora_clima: tudo certo!

In [30]:
# Compara as linhas usando o método equals do Pandas (mais rigoroso)
print(f"Linha 0 é idêntica à 2? {df.iloc[0:1].equals(df.iloc[2:3])}")

# Mostra se há NaNs escondidos que podem estar quebrando a lógica
print("\nContagem de nulos nas linhas:")
print(df.iloc[[0, 2]].isna().sum(axis=1))

# Tente converter tudo para string temporariamente e testar
temp_duplicados = df.astype(str).duplicated(keep=False)
print(f"\nSe eu converter tudo para STRING, a linha 2 vira duplicada? {temp_duplicados.iloc[2]}")

Linha 0 é idêntica à 2? False

Contagem de nulos nas linhas:
0    0
2    0
dtype: int64

Se eu converter tudo para STRING, a linha 2 vira duplicada? True

In [3]:
import pandas as pd
pd.read_csv(r"C:\Users\Pichau\OneDrive\Documentos\Estudos Dudu\7. atraso-voos\data\arquivos_voos\2025\01 - Janeiro\VRA_20251.csv", skiprows=1, sep=';', low_memory=False)

,ICAO Empresa Aérea,Número Voo,Código Autorização (DI),Código Tipo Linha,ICAO Aeródromo Origem,ICAO Aeródromo Destino,Partida Prevista,Partida Real,Chegada Prevista,Chegada Real,Situação Voo,Código Justificativa
0,GLO,1518,0,N,SBBR,SBTE,2025-01-03 00:55:00,2025-01-03 00:50:00,2025-01-03 03:10:00,2025-01-03 02:51:00,REALIZADO,NaN
1,GLO,1518,0,N,SBBR,SBTE,2025-01-04 00:55:00,2025-01-04 00:46:00,2025-01-04 03:10:00,2025-01-04 02:51:00,REALIZADO,NaN
2,GLO,1518,0,N,SBBR,SBTE,2025-01-05 00:55:00,2025-01-05 00:50:00,2025-01-05 03:10:00,2025-01-05 02:59:00,REALIZADO,NaN
3,GLO,1518,0,N,SBBR,SBTE,2025-01-06 00:55:00,2025-01-06 00:52:00,2025-01-06 03:10:00,2025-01-06 03:02:00,REALIZADO,NaN
4,GLO,1518,0,N,SBBR,SBTE,2025-01-07 00:55:00,2025-01-07 00:42:00,2025-01-07 03:10:00,2025-01-07 02:41:00,REALIZADO,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
89711,TAM,8106,0,I,SBGL,SCEL,2025-01-31 12:50:00,2025-01-31 12:43:00,2025-01-31 17:40:00,2025-01-31 17:04:00,REALIZADO,NaN
89712,TAM,8112,0,I,SBGR,MMMX,2025-01-05 23:40:00,2025-01-05 23:47:00,2025-01-06 08:55:00,2025-01-06 08:51:00,REALIZADO,NaN
89713,TAM,8107,0,I,SCEL,SBGL,2025-01-01 18:25:00,2025-01-01 18:20:00,2025-01-01 22:40:00,2025-01-01 22:25:00,REALIZADO,NaN
89714,TAM,8107,0,I,SCEL,SBGL,2025-01-02 18:25:00,2025-01-02 18:35:00,2025-01-02 22:40:00,2025-01-02 22:44:00,REALIZADO,NaN
89715,TAM,8107,0,I,SCEL,SBGL,2025-01-03 18:25:00,2025-01-03 18:36:00,2025-01-03 22:40:00,2025-01-03 22:26:00,REALIZADO,NaN